api/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from api import  views

urlpatterns = [
    url(r'^ticket', views.geraTicketAPI),
    url(r'^consultar', views.consultaTicketAPI),
    url(r'^editar', views.editaTicketAPI),
    url(r'^excluir', views.deletaTicketAPI),
    url(r'^$', views.inicial),
    url(r'^edit', views.alterar),
    url(r'^delete/(?P<id>[0-9]+)/$', views.deletar, name='deletar_api'), 
]

sica/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from core import views

admin.autodiscover()

urlpatterns = [
    url(r'^admin', include(admin.site.urls)),
    url(r'^home', views.home),
    url(r'^core/login', views.sica_login),
    url(r'^logout', views.sica_logout),
    url(r'^horarios/',  include('horario.urls')),
    url(r'^alunos/',  include('aluno.urls')),
    url(r'^cardapio/',  include('core.urls')),
    url(r'^cursos/',  include('curso.urls')),
    url(r'^relatorio/',  include('relatorio.urls')),
    url(r'^cotas/',  include('cota.urls')),
    url(r'^creditos/',  include('creditos.urls')),
    url(r'^$', views.home),
    url(r'accounts/login/', views.accountsLogin),
    url(r'accounts/password/', views.accountsPassword),
    url(r'^api/', include('api.urls')),
    url(r'^usuarios/',  include('usuarios.urls')),
]

api/models.py
# -*- coding: utf-8 -*-

from django.db import models

class CodigoSegurancaApi(models.Model):
    sistema = models.TextField(max_length=100)
    codigo = models.CharField(max_length=10, default="Inválido", unique=True)
    data = models.DateField(u'Data de Criação', auto_now_add=True)

api/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required, permission_required
from django.views.decorators.csrf import csrf_exempt
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from relatorio.models import Ticket
from aluno.models import Aluno
from api.models import CodigoSegurancaApi
import hashlib, time

def createHash():
    codigo = hashlib.sha1()
    codigo.update(str(time.time()))
    return codigo.hexdigest()[:10] 

@login_required(login_url='/accounts/login/')
@permission_required('api.add_api', raise_exception=True)
def inicial(request):
    sistemas = CodigoSegurancaApi.objects.all()
    logado =  False
    
    if request.user.is_active:
        logado =  True
    
    if request.method == "POST":
        controle = 0
        
        while controle != 1:
            codigoHash = createHash()
            
            instancias = CodigoSegurancaApi.objects.filter(codigo=codigoHash).count()
            
            if instancias == 0:
                controle = 1
             
        codigo = CodigoSegurancaApi(
            sistema = request.POST.get("sistema"),
            codigo = codigoHash
        )
        
        codigo.save()
        
        return render(request, 'api/api.html', {'sistemas': sistemas, 'msg': 'Código de Acesso gerado com sucesso', 'logado': logado})
    else:
        if '0' in request.session:
            msg = request.session['0']
            del request.session['0']
            
            return render(request, 'api/api.html', {'sistemas': sistemas, 'logado': logado, 'msg': msg})
        
        if '1' in request.session:
            msg = request.session['1']
            del request.session['1']
            
            return render(request, 'api/api.html', {'sistemas': sistemas, 'logado': logado, 'err': msg})
        
        return render(request, 'api/api.html', {'sistemas': sistemas, 'logado': logado})

@login_required(login_url='/accounts/login/')
@permission_required('api.add_api', raise_exception=True)
def alterar(request):
    if request.method == "POST":
        sistema = request.POST.get("sistema")
        identificador = request.POST.get("id")
        
        codigo = CodigoSegurancaApi.objects.filter(id=identificador)
    
        if codigo.count() == 1:
            codigo = codigo.first()
            
        controle = 0
        
        while controle != 1:
            codigoHash = createHash()
            
            instancias = CodigoSegurancaApi.objects.filter(codigo=codigoHash).count()
            
            if instancias == 0:
                controle = 1
            
        codigo.sistema = sistema
        codigo.codigo = codigoHash
        
        codigo.save()
        
        request.session[0] = "Chave de Integração Atualizada com sucesso"
        return redirect("/api")
    else:
        request.session[1] = "Erro de acesso a página"
        return redirect("/api")

@login_required(login_url='/accounts/login/')
@permission_required('api.add_api', raise_exception=True)
def deletar(request, id):
    codigo = CodigoSegurancaApi.objects.filter(id=id)
    
    if codigo.count() == 1:
        codigo = codigo.first()
        codigo.delete()
        
    request.session[0] = "Vinculo de Sistema deletado com sucesso"
    
    return redirect("/api")

def buscaAluno(prontuario):
    if u'PE' in prontuario.upper() and len(prontuario) == 9:
        prontuario = prontuario[2:]            
        
    aluno = Aluno.objects.filter(prontuario__icontains=prontuario, ativo=True)
    
    return aluno

def ticketDIC(tickets):
    dicionario = {}
    aux = 0
    
    for ticket in tickets:
        prontuario = ticket.aluno.prontuario
        data = dict(year=ticket.data.day, month=ticket.data.month, day=ticket.data.year)
        tipo = ticket.tipo
        
        dicionario.update({aux:{"prontuario": prontuario, "data": data, "tipo": tipo}})
        aux+=1
        
    return dicionario

@csrf_exempt
def geraTicketAPI(request):
    if request.method == 'POST':
        prontuario = request.POST.get("prontuario")
        data = request.POST.get("data")
        chave = request.POST.get("chave")
        
        codigo = CodigoSegurancaApi.objects.filter(codigo=chave)
        
        if codigo.count() != 0:
            aluno = buscaAluno(prontuario)
            
            if aluno.count() == 1:
                aluno = aluno.first()
                ticket = Ticket.objects.filter(aluno__id__icontains=aluno.id, data__icontains=data)
                    
                if ticket.count() == 0:
                    ticket = Ticket(
                        aluno = aluno,
                        data = data,
                        tipo = 2,
                    )
                        
                    ticket.save()
                    
                    return JsonResponse({'status': 1, 'msg': 'Ticket Salvo com Sucesso'})
                else:
                    return JsonResponse({'status': 0, 'msg': 'Ticket Gerado Anteriormente'})
            else:
                return JsonResponse({'status': 0, 'msg': 'Nenhum Aluno Encontrado'})
        else:
            return JsonResponse({'status': 0, 'msg': 'Chave de Integração Incorreta'})
    else:
        return JsonResponse({'status': 0, 'msg': 'Erro de Requisição'})
                
@csrf_exempt
def consultaTicketAPI(request):
    if request.method == 'POST':
        prontuario = request.POST.get("prontuario")
        chave = request.POST.get("chave")
        
        codigo = CodigoSegurancaApi.objects.filter(codigo=chave)
        
        if codigo.count() != 0:
            aluno = buscaAluno(prontuario)
            
            if aluno.count() == 1:
                aluno = aluno.first()
                tickets = list(Ticket.objects.filter(aluno__id__icontains=aluno.id, tipo=0))
                
                return JsonResponse({'status': 1, 'tickets': ticketDIC(tickets)})
            else:
                return JsonResponse({'status': 0, 'msg': 'Nenhum Aluno Encontrado'})
        else:
            return JsonResponse({'status': 0, 'msg': 'Chave de Integração Incorreta'})
    else:
        return JsonResponse({'status': 0, 'msg': 'Erro de Requisição'})

@csrf_exempt
def deletaTicketAPI(request):
    if request.method == 'POST':
        prontuario = request.POST.get("prontuario")
        data = request.POST.get("data")
        chave = request.POST.get("chave")
        
        codigo = CodigoSegurancaApi.objects.filter(codigo=chave)
        
        if codigo.count() != 0:
            aluno = buscaAluno(prontuario)
            
            if aluno.count() == 1:
                aluno = aluno.first()
                
                ticket = Ticket.objects.raw("SELECT * FROM relatorio_ticket where data = TO_DATE('"+data+"', 'YYYY-MM-DD') AND aluno_id = "+str(aluno.id))
                ticket = list(ticket)
                
                if len(ticket) == 1:
                    ticket = ticket[0]
                else:
                    return ({'status': 0, 'msg': 'Há mais de um ticket gerado para este aluno para a data informada'})
            
                ticket.delete()
                
                return JsonResponse({'status': 1, 'msg': 'Data do Ticket Deletado com Sucesso'})
        else:
            return JsonResponse({'status': 0, 'msg': 'Chave de Integração Incorreta'})
    else:
        return JsonResponse({'status': 0, 'msg': 'Erro de Requisição'})

@csrf_exempt    
def editaTicketAPI(request):
    if request.method == 'POST':
        prontuario = request.POST.get("prontuario")
        dataAtual = request.POST.get("data")
        dataNova = request.POST.get("dataNova")
        chave = request.POST.get("chave")
        
        codigo = CodigoSegurancaApi.objects.filter(codigo=chave)
        
        if codigo.count() != 0:
            aluno = buscaAluno(prontuario)
            
            if aluno.count() == 1:
                aluno = aluno.first()
                
                ticket = Ticket.objects.raw("SELECT * FROM relatorio_ticket where data = TO_DATE('"+dataAtual+"', 'YYYY-MM-DD') AND aluno_id = "+str(aluno.id))
                aux = Ticket.objects.raw("SELECT * FROM relatorio_ticket where data = TO_DATE('"+dataNova+"', 'YYYY-MM-DD') AND aluno_id = "+str(aluno.id))
                
                ticket = list(ticket)
                aux = list(aux)
                
                if len(ticket) == 1:
                    ticket = ticket[0]
                else:
                    return ({'status': 0, 'msg': 'Há mais de um ticket gerado para este aluno para a data informada'})
                
                if len(aux) != 0:
                    return ({'status': 0, 'msg': 'Um ticket já foi gerado para o aluno na data informada'})
                
                ticket.data = dataNova
                
                ticket.save()
                
                return JsonResponse({'status': 1, 'msg': 'Data do Ticket Editado com Sucesso'})
            else:
                return JsonResponse({'status': 1, 'msg': 'Mais de um aluno foi encontrado'})
        else:
            return JsonResponse({'status': 0, 'msg': 'Chave de Integração Incorreta'})
    else:
        return JsonResponse({'status': 0, 'msg': 'Erro de Requisição'})

templates/api/api.html
{% extends 'base.html' %}

{% block titulo %}SICA|API{% endblock %}

{% block content %}
<div class="container">
	{% if msg %}
	<div class="row">
		<div class="col-md-12">
			<div class="alert alert-success alert-dismissable fade in">
    			<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    			<strong>Tudo Certo! {{msg }}.
  			</div>
		</div>
	</div>
	{% endif %}
	{% if err %}
	<div class="row">
		<div class="col-md-12">
			<div class="alert alert-danger alert-dismissable fade in">
    			<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    			<strong>Que pena! {{ err }}.
  			</div>
		</div>
	</div>
	{% endif %}
	<legend>Sistemas Integrados</legend>
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-primary">
				{% if sistemas %}
				<div class="panel-heading">
					Registros Apresentados: {{sistemas.count}}
				</div>
				{% else %}
				<div class="panel-heading">
				</div>
				{% endif %}
				<table class="table">
					<tr>
						<th>Sistema</th>
						<th>Hash Gerado</th>
						<th>Data</th>
						<th>Ações</th>
					</tr>
					{% for sistema in sistemas %}
					<tr>
						<th>{{ sistema.sistema }}</th>
						<th>{{ sistema.codigo }}</th>
						<th>{{ sistema.data }}</th>
						<th>
							<a data-toggle="modal" data-target="#alterar{{sistema.id}}" class="glyphicon glyphicon-edit"></a>
							<a data-toggle="modal" data-target="#sistema{{sistema.id}}" class="glyphicon glyphicon-remove"></a>
						</th>
					</tr>
					{% endfor %}
				</table>
			</div>
		</div>
	</div>
	<a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    	Gerar Chave de Integração
  	</a>
	<p>
		<div class="collapse" id="collapseExample">
	  		<div class="card card-body">
	    		<form role="form"  method="post" class="login-form">
				{% csrf_token %}
					<div class="row">
						<div class="col-md-4">
							<div class="form-group">
								<label for="prontuario">Sistema:</label>
								<input type="text" name="sistema" id="id_sistema" maxlength="100" required>
							</div>
						</div>
					</div>
					<button type="submit" class="btn btn-primary glyphicon glyphicon-plus-sign"><font face="Arial"><b> Adicionar</b></font></button>
				</form>
	  		</div>
		</div>
	</p>
<!-- Modal -->
{% for sistema in sistemas %}
	<div class="modal fade" id="sistema{{sistema.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  		<div class="modal-dialog" role="document">
    		<div class="modal-content">
      			<div class="modal-header">
        			<h5 class="modal-title" id="exampleModalLabel">Revogar Chave de Acesso</h5>
      			</div>
      			<div class="modal-body">
      				Realmente deseja apagar a chave de integração para o sistema {{sistema.sistema}}?
      			</div>
      			<div class="modal-footer">
      				<a href="{% url 'deletar_api' id=sistema.id %}">
      					<button type="button" class="btn btn-secondary">Aceitar</button>      				
      				</a>
        			<button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>	
      			</div>
    		</div>
  		</div>
	</div>
	<div class="modal fade" id="alterar{{sistema.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  		<div class="modal-dialog" role="document">
    		<div class="modal-content">
      			<div class="modal-header">
        			<h5 class="modal-title" id="exampleModalLabel">Alterar Nome do Sistema</h5>
      			</div>
      			<div class="modal-body">
      				<p>
      					Nome Atual: {{sistema.sistema}}
      				</p>
					<p>
      					*A troca do nome do sistema implicará na troca da chave de integração.
      				</p>
					<form action="/api/edit" method="post">
      				{% csrf_token %}
      					<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label for="prontuario">Sistema:</label>
									<input type="text" name="sistema" id="id_sistema" maxlength="100" required>
								</div>
							</div>
						</div>
						<input type="hidden" name="id" id="id" value="{{sistema.id}}">
						<button type="submit" class="btn btn-primary"><font face="Arial"><b>Alterar</b></font></button>
      				</form>
      			</div>
      			<div class="modal-footer">
        			<button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>	
      			</div>
    		</div>
  		</div>
	</div>
{% endfor %}	
</div>
{% endblock %}

{% block script %}
	$('#myModal').on('shown.bs.modal', function () {
  		$('#myInput').trigger('focus')
	})
{% endblock %}